<?php

namespace Videl\DetailsBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MenuRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MenuRepository extends EntityRepository
{
	public function findAllOrderedByPosition()
	{
		return $this->getEntityManager()->createQuery(
            'SELECT m FROM VidelDetailsBundle:Menu m ORDER BY m.position'
            )->getResult();
	}
}
